[build]
  command = "npm ci && npm run build"
  functions = "functions"
  publish = "public"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  included_files = ["dist/**"]

[functions.api]
  timeout = 30
  external_node_modules = ["@prisma/client", ".prisma/client"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/api/health"
  status = 200

[[redirects]]
  from = "/success"
  to = "/.netlify/functions/api/success"
  status = 200

[[redirects]]
  from = "/cancel"
  to = "/.netlify/functions/api/cancel"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization" 